# Generated by Django 4.2.13 on 2024-06-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
